DAGs: migration fro  requests lib to http hook
cern-sis/bi-dags pull request #32
Opened 2024-07-09 10:20 UTC by ErnestaP

2024-07-29 07:32 UTC, drjova requested changes
🙏 few comments

2024-07-29 07:32 UTC, drjova commented on dags/library/utils.py
> +        "publications_total_count": r"search?wl=0&ln=en&cc=Published+"
these are not urls any more, these are endpoints :)

2024-07-29 07:32 UTC, drjova commented on dags/library/cern_publication_records.py
> +                "retry": retry_if_exception_type(Exception),
I would retry on request related exceptions, to avoid hiding underlying issues

2024-07-31 09:32 UTC, drjova requested changes

2024-07-31 09:37 UTC, ErnestaP commented on dags/library/cern_publication_records.py
> +    @task
yes, we do! Adding it

2024-07-31 09:39 UTC, ErnestaP commented on dags/open_access/open_access.py
> +        query_p = rf"{base_query}+{query[type_of_query]}"
sure. query_p - p means that it's a query that goes in `p` parameter of the endpoint:
```
        return {
            "endpoint": rf"search?ln=en&cc={current_collection}&p={query_p}"
            + r"&action_search=Search&op1=a&m1=a&p1=&f1=&c="
            + r"Published+Articles&c=&sf=&so=d&rm=&rg=100&sc=0&of=xm",
            "type_of_query": type_of_query,
        }
```

2024-07-31 12:44 UTC, drjova commented on tests/open_access/test_data_harvesting.py
this file is empty

2024-07-31 12:45 UTC, drjova commented on dags/library/cern_publication_records.py
> -from common.utils import get_total_results_count, request_again_if_failed
can completely remove `request_again_if_failed`?

2024-07-31 12:50 UTC, ErnestaP commented on dags/library/cern_publication_records.py
> -from common.utils import get_total_results_count, request_again_if_failed
it is removed

2024-07-31 13:18 UTC, drjova approved these changes

2024-07-31 13:19 UTC, merged